#!/bin/sh

if [ -z "${ARADINE_HOME}" ]
then
  echo "ARADINE_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
--enable-native-access=org.xerial.sqlitejdbc \
-p "${ARADINE_HOME}/lib" \
-m com.io7m.aradine.cmdline/com.io7m.aradine.cmdline.ARCMain \
"$@"
